
//asw_globals.js : Contains global variables used across WPD.

var g_myVar,
    g_context_opened = "N",
    g_area_zoom_ind = "N",
    g_select_zoom_arr = [],
    g_pogjson_backup = [],
    g_pogjson_data_backup = [], //ASA-1914 Issue5.3
    g_default_checkbox,
    g_taskItemInContext1,
    g_pog_edited_ind,
    g_multi_shelf_index = -1,
    g_multi_shelf_ind = "N",
    g_multi_mod_index = "",
    g_multi_shelf_obj_type = "",
    g_multi_shelf_arr = [],
    g_multi_delete_shelf_ind = "N",
    g_multi_delete_done = "N",
    g_clearInfoType = "N",
    g_edit_ind,
    g_db,
    g_fileDownloadCheckTimer,
    g_trs,
    g_object_hit_ind = "O",
    g_temp_cut_arr = [],
    g_multiselect = "N",
    g_taskItemInContext,
    g_errored_items = [],
    g_error_category = "",
    g_mousedown_locx,
    g_auto_position_ind = "N",
    g_hangbar_dft_maxmerch,
    g_pegboard_dft_item_depth,
    g_pdf_online_clck = "N",
    g_dupShelfDepth = 0.1,
    g_auto_fill_active = "N",
    g_mod_block_list = [],
    g_temp_image_arr = [],
    g_pegbrd_auto_placing,
    g_multiItemCopy = "N",
    g_canvas_drag = "N",
    g_mselect_drag = "N",
    g_start_canvas = 1,
    g_present_canvas = 1,
    g_ctrl_select = "N",
    g_dragging = false,
    g_selecting = false,
    g_product_list_drag = "N",
    g_item_edit_flag = "N",
    g_dblclick_opened = "N",
    g_pogcr_pdf_chest_split,
    g_minvalue = 0.01,
    g_nodataModuleName,
    g_lr_overhung,
    g_pog_json_comp,
    g_new_canvas,
    g_fileUploadFlag = "N",
    g_shelf_index = -1,
    g_module_index = 0,
    g_final_x = 0,
    g_final_y = 0,
    g_final_z = 0,
    g_wireframe_id,
    g_isBookend = "N",
    g_shelf_object_type,
    g_movedObjID = -1,
    g_objectHit_id,
    g_lines = [], // for function fitText
    g_peg_holes_active = "Y",
    g_module_width,
    g_world_pdf,
    g_dblclick_objid,
    g_compare_pog_flag = "N",
    g_ComViewIndex = -1,
    g_ComBaseIndex = -1,
    g_compare_view = "NONE",
    g_slope = 0,
    g_manual_zoom_ind = "N",
    g_show_fixel_label = "N",
    g_edit_pallet_shelfid = -1,
    g_show_notch_label = "N",
    g_shelf_edit_flag = "N",
    g_show_item_label = "N",
    g_show_peg_tags = "N",
    g_carpark_item_flag = "N",
    g_ItemImages = [],
    g_auto_cal_depth_fac = "N", //ASA-1255
    g_deletedItems = [],
    g_l_module_dir,
    g_l_direction,
    g_l_ignore,
    g_l_order_type,
    g_l_start_one_mod,
    g_l_include_mod_name,
    g_l_separator,
    g_l_leading_text,
    g_l_trailing_text,
    g_l_start_one_mod_loc,
    g_l_start_one_fixel,
    g_keyCode = 0,
    g_cutaway_cam_detail = [],
    g_prev_undo_action = "NONE",
    g_duplicate_fixel_flag = "N",
    g_shelf_basket_spread = "",
    g_carpark_items = [],
    g_show_days_of_supply,
    g_get_orient_images,
    g_drag_shelf_notch,
    g_show_notch_label_comp = "N",
    g_cut_loc_arr = [],
    g_undo_obj_arr = [],
    g_undo_supp_obj_arr = [],
    g_redo_supp_obj_arr = [],
    g_undoRedoAction,
    g_undo_details = [],
    g_delete_details = [],
    g_undo_all_obj_arr = [],
    g_cut_support_obj_arr = [],
    g_multi_drag_shelf_arr = [],
    g_multi_drag_item_arr = [],
    g_cut_copy_arr = [],
    g_redo_all_obj_arr = [],
    g_multi_copy_done = "N",
    g_redo_final_obj_arr = [],
    g_curr_canvas = 1,
    g_pog_index = -1,
    g_auto_fill_reg_open = "N",
    g_comp_view_code = "",
    g_comp_base_code = "",
    g_productselect = "N",
    g_scene_objects_backup = [],
    g_labelFont = 16,
    g_validationFlag = "Y",
    g_cut_action_done = "N",
    g_copy_action_done = "N",
    g_dup_action_done = "N",
    g_delete_action_done = "N",
    g_labelActualSize = 0.055,
    g_status_error_color,
    g_offset_z,
    g_pegbrd_auto_placing = "N",
    g_edited_item_index = -1,
    g_upload_file_flag = "N",
    g_drag_items_arr = [],
    g_itemDragZ = 0,
    g_allUndoObjectsInfo = [],
    g_dup_mod_list = [],
    g_pog_json_data = [],
    g_dft_max_merch = 0, //ASA1310_20240307 crush item onload
    //g_pegboard,global variables to be removed and changed to local
    //g_shelf,
    //g_module,
    //g_notches1,
    //g_notches2,
    g_temp_POG_arr,
    g_textbox_merge_pdf,
    g_auto_hangbar_facings,
    g_auto_apply_v_facings,
    g_auto_apply_d_facings,
    g_windowHeight,
    g_windowWidth,
    g_tanFOV,
    g_undo_final_obj_arr = [],
    g_rotation = 0,
    g_show_live_image = "N",
    g_show_item_desc = "N",
    g_module_obj_array = [],
    g_all_pog_flag = "N",
    g_temp_desc = "N",
    g_drag_x,
    g_drag_z,
    g_targetForDragging, // An invisible object that is used as the target for raycasting while
    g_dim_error_color,
    g_dbuDebugEnabled = sessionStorage.getItem("g_dbuDebugEnabled"),
    g_pogBackup = [],
    g_errorRaisedFlag = "N",
    g_openChooseColor = false,
    g_scene_pdf,
    g_camera_pdf,
    g_renderer_pdf,
    g_nonMovingItemColor = parseInt("#9F2B68".replace("#", "0x"), 16),
    g_pogcr_auto_hlite_non_mv_item,
    g_show_item_desc_comp = "N",
    g_show_live_image_comp = "N",
    g_raycaster, // A THREE.Raycaster for user mouse input.
    g_camera_comp,
    g_world_comp,
    g_show_desc_no_image,
    g_caption_text = "",
    g_intersected = [],
    g_notch_label_position,
    g_edit_pallet_mod_ind = -1,
    g_edit_pallet_shelf_ind = -1,
    g_open_productlist = "Y",
    g_delete_item_json = [],
    g_combinedShelfs = [], //ASA-1129
    g_combineItemModf = [], //ASA-1129
    g_overhung_validation,
    g_seqArr = [],
    g_seqArrDtl = {},
    g_renum_json = [],
    g_multi_pog_json = [],
    g_overhung_shelf_active = "N",
    g_ispog_savingerror = "N",
    g_counting = 0,
    g_pog_saving_error_msg = "N",
    g_canvas,
    g_canvas_region,
    g_scene,
    g_renderer,
    g_camera,
    g_initial_camera, //ASA-2048 Issue 8
    g_select_color = 0x000000,
    g_orientation_json,
    g_start_pixel_ratio,
    g_selection,
    g_scene_objects = [],
    g_canvas_objects = [],
    g_json = [],
    g_world,
    g_pog_json = [],
    g_fixel_label = "N",
    g_vert_text_dis = 0,
    g_pog_list = [],
    g_objectHit_uuid,
    g_global_counter = 0,
    g_intersects,
    g_start_coorX,
    g_start_coorY,
    g_objectHit,
    g_chest_as_pegboard = "N",
    g_lastSelectedRow,
    g_dragItem,
    g_draftPogInd = "",
    g_finalY = -1,
    g_prevX = 0,
    g_recal_compare = "N", //asa-1170
    g_prevY = 0,
    g_isPogItemsSet = "N",
    g_colorBackup = "N",
    g_imagesShown = "N",
    g_imagesShownComp = "N",
    g_validationAlert = "N",
    g_prevKeyPressed = 0,
    g_max_facing_enabled = "N",
    g_item_index,
    g_current_div_index = "",
    g_incre_mod_index,
    g_incre_shelf_index,
    g_incre_item_index,
    g_status_bar = [],
    g_shelf_max_merch,
    g_itemDragX = -1,
    g_drag_inprogress = "N",
    g_module_X,
    g_module_cnt,
    g_module_edit_flag = "N",
    g_carpark_edit_flag = "N",
    g_show_max_merch = "N",
    g_show_item_color = "N",
    g_show_fixel_space,
    g_pog_refresh_msg = get_message("POG_SAVE_SUCCESS_MSG"),
    g_pog_draft_save_msg = get_message("SAVE_DRAFT_SUCESS_MSG"),
    g_delete_success_msg = get_message("DELETE_SUCCESS_MSG"),
    g_pog_success_msg = get_message("SAVE_POG_SUCESS_MSG"),
    g_atleast_one_pog = get_message("ATLEAST_ONE_POG"),
    g_expand_all_pog = get_message("POGCR_EXPAND_ALL_POG"),
    g_msg_na = get_message("POGCR_MSG_NA"), //ASA-1407 Task 1 -S
    g_msg_h = get_message("POGCR_MSG_H"),
    g_msg_w = get_message("POGCR_MSG_W"),
    g_msg_d = get_message("POGCR_MSG_D"),
    g_msg_Sq = get_message("POGCR_MSG_SQ"),
    g_msg_unit = get_message("POGCR_MSG_UNIT"),
    g_msg_dollar = get_message("POGCR_MSG_DOLLAR"), //ASA-1407 Task 1 -E
    g_itemSubLabelInd = "N",
    g_itemSubLabel = "",
    g_shelf_details = [],
    g_color_arr = [],
    g_highlightArr = [],
    g_duplicating = "N",
    g_autofill_edit = "N",
    g_show_error = true,
    g_invalidPosition = "N",
    g_pogcr_live_new_item = "N",
    g_shift_mutli_item_select = "N", //ASA-1422
    g_shift_multi_item_first = {}, //ASA-1422
    g_shift_multi_item_last = {}, //ASA-1422
    g_multi_select_offset_perc = 0, //ASA-1422
    g_hide_show_dos_label = "", //ASA-1427
    g_itemInfoFileIndex = 0, //ASA-1446
    g_sublabel_type = "", //ASA-1533
    g_toFixedValue, //ASA-1472
    g_show_plano_rate = "N", //ASA-1587
    g_product_list_blink = "N", //ASA-1640
    g_multi_cnvs_drag_conf = "N", //ASA-1640
    g_item_stack_valid = "Y", //ASA-1652
    g_item_shelf_updated_msg = get_message("POGCR_ITEM_FIXEL_UPD"), //ASA-1669
    g_is_pog_template_open = "N", //ASA-1694
    g_autofill_detail = {}, //ASA-1694
    g_wf_pog_approval_enabled = "", //Regression 5 20250217
    g_pogcr_pog_approval_for_new_pog = "", //Regression 5 20250217
    g_pogcr_enbl_oos_border, //ASA-1688
    g_pogcr_oos_border_color, //ASA-1688
    g_pogcr_enhance_textbox_fontsize, //ASA-1787 
    g_is_pog_maximize = "N", // ASA-1898 
    g_textbox_dragged = "N", // ASA-2000.15
    g_edit_textboxZ = ""; //ASA-2029.1.4
var g_autofillModInfo = [],
    g_autofillShelfInfo = []; //ASA-1697
    g_item_vertical_text_display = "Y", //ASA-1847 4.1
    g_item_text_center_align = "Y"; //ASA-1847 4.1
var g_DragMouseStart = new THREE.Vector2();
var g_DragMouseEnd = new THREE.Vector2();
var g_mouse = new THREE.Vector2();
var g_startMouse = new THREE.Vector2();
var g_prevMouse = new THREE.Vector2();
var g_nextMouse = new THREE.Vector2();
var g_allowItemSort = "Y"; //ASA-1970 Issue1